In [2]:
# NumPy arrays are the main way we will use Numpy throughout the course. 
# Numpy arrays essentially come in two flavors: vectors and matrices. 
# Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a 
# matrix can still have only one row or one column).NumPy arrays are the main 
# way we will use Numpy throughout the course. Numpy arrays essentially come 
# in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and 
# matrices are 2-d (but you should note a matrix can still have only one row 
# or one column).

In [27]:
my_list = [1,2,3]

In [28]:
my_list

[1, 2, 3]

In [29]:
import numpy as np

In [30]:
arr = np.array(my_list)

In [31]:
arr

array([1, 2, 3])

In [32]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [33]:
my_mat   # You get back a list of lists

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [34]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(0,11,2)   # You jump a step size of 2

array([ 0,  2,  4,  6,  8, 10])

In [13]:
# arange is going to be one of the most useful functions for quickly generating
# an array using numpy

In [14]:
np.zeros(3)

array([0., 0., 0.])

In [15]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
np.linspace(0,5,10)   # These will be 10 evenly spaced points

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [18]:
# Identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [19]:
np.random.rand(5)

array([0.70416837, 0.23312412, 0.05649848, 0.16251949, 0.3619702 ])

In [20]:
np.random.rand(5,5)

array([[0.74022471, 0.01751278, 0.00957344, 0.18231886, 0.07324101],
       [0.9319655 , 0.05108362, 0.9738344 , 0.07953035, 0.66235722],
       [0.79797743, 0.64174447, 0.0808529 , 0.82860114, 0.24397422],
       [0.61025883, 0.31780645, 0.06619306, 0.82113049, 0.0505671 ],
       [0.13001931, 0.6080276 , 0.3345566 , 0.97935447, 0.91776083]])

In [21]:
np.random.randn(5)   # This will return numbers from a standard normal 
# distribution center around zero

array([ 0.58438424, -0.52090509, -0.36486202, -0.64255417,  0.99035649])

In [22]:
np.random.randn(4,4)

array([[-0.16722364, -0.92362123, -0.77106477, -0.86118972],
       [ 1.3305473 , -0.09622778,  1.71134549,  0.71306389],
       [ 0.67220287, -0.77063557, -1.67864804, -2.35662938],
       [-0.84482668,  0.93871984,  0.48683557,  0.02577919]])

In [23]:
np.random.randint(1,100)   # 1 can be selected but not 100

93

In [24]:
np.random.randint(1,100,10)

array([39, 75, 35, 19, 97, 92, 88, 40, 23, 24])

In [25]:
arr = np.arange(25)

In [26]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [27]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [28]:
arr.reshape(5,10)

ValueError: cannot reshape array of size 25 into shape (5,10)

In [29]:
ranarr = np.random.randint(0,50,10)

In [30]:
ranarr

array([43, 28, 40,  6, 25, 18, 46, 39, 20, 33])

In [31]:
ranarr.max()

46

In [32]:
ranarr.min()

6

In [35]:
ranarr.argmax()

6

In [37]:
ranarr.argmin()

3

In [38]:
arr.shape

(25,)

In [39]:
arr = arr.reshape(5,5)

In [40]:
arr.shape

(5, 5)

In [41]:
arr.dtype

dtype('int32')

In [42]:
from numpy.random import randint

In [43]:
randint(2,10)

2

In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[8]

8

In [5]:
arr[1:5]

array([1, 2, 3, 4])

In [7]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [8]:
arr[:5]

array([0, 1, 2, 3, 4])

In [9]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [10]:
arr[0:5] = 100

In [11]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [13]:
arr = np.arange(0,11)

In [14]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
slice_of_arr = arr[0:6]

In [16]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [17]:
slice_of_arr[:] = 99

In [18]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [19]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [20]:
arr_copy = arr.copy()

In [21]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [22]:
arr_copy[:] = 100

In [23]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [24]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [25]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [26]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [37]:
arr_2d[0][2]

15

In [38]:
arr_2d[0,2]

15

In [36]:
arr_2d[1]

array([20, 25, 30])

In [39]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [40]:
arr = np.arange(1,11)

In [41]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
bool_arr = arr > 5

In [44]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [45]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [46]:
arr[arr > 5]

array([ 6,  7,  8,  9, 10])

In [47]:
arr_new = np.arange(50).reshape(5,10)

In [48]:
arr_new

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [49]:
import numpy as np

In [50]:
arr = np.arange(0,11)

In [51]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [52]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [53]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [54]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [55]:
arr + 100   # Same for subtraction and multiplication

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [56]:
1/0

ZeroDivisionError: division by zero

In [57]:
arr/arr

C:\Users\0902s\AppData\Local\Temp/ipykernel_1868/1862401812.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [58]:
1/arr

C:\Users\0902s\AppData\Local\Temp/ipykernel_1868/255282349.py:1: RuntimeWarning: divide by zero encountered in true_divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [59]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [60]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [61]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [62]:
np.max(arr)

10

In [63]:
arr.max()

10

In [64]:
np.log(arr)

C:\Users\0902s\AppData\Local\Temp/ipykernel_1868/3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])